#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:
#	displays 4 and then bad luck from China for the 4th loop iteration
#	displays 9 and then bad luck from Japan for the 9th loop iteration
#	displays 17 and then bad luck from Italy for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
	if [ $count -eq 4 ]; then
		echo $count
		echo "bad luck from China"
	elif [ $count -eq 9 ]; then
		echo $count
		echo "bad luck from Japan"
	elif [ $count -eq 17 ]; then
		echo $count
		echo "bad luck from Italy"
	else
		echo $count
	fi
	count=$((count+1))
done
