#!/usr/bin/env bash
#Bash script that displays:
#	The content of the current directory
#	In a list format
#	only the part of the name after the first dash


for file in *; do
	if [[ ! $file == .* && -f $file ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
